name: CI Tests

on:
  push:
    branches: [ main ]

jobs:
  test-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vérifier index3.html
        run: |
          if [ ! -f index.html ]; then
            echo "index.html manquant"
            exit 1
          fi

      - name: Vérifier contenu page
        run: |
          grep "TP DevOps" index3.html
